name: Update flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Runs weekly on monday at 00:00

jobs:
  update-flake:
    name: Update flake
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Update flake.lock
        run: |
          nix flake update --flake .
          nix flake update --flake ./dev
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          assignees: HeitorAugustoLN
          branch: update-flake-lock
          commit-message: "chore(deps): update flake.lock"
          delete-branch: true
          labels: dependencies
          reviewers: HeitorAugustoLN
          title: "chore(deps): update flake.lock"
